const router = require('express').Router();
const { planOf } = require('../middleware/auth');
const ai = require('../ai');
const { awardXP } = require('../xp');

router.get('/', async (req, res, next) => {
  try {
    const { data: ideas } = await req.sb.from('generated_ideas').select('*')
      .eq('user_id', req.user.id).order('position', { ascending: true });
    const { data: q } = await req.sb.from('questionnaire_responses').select('id, completed').eq('user_id', req.user.id).maybeSingle();
    res.render('ideas', { title: 'Your Business Ideas', ideas: ideas || [], hasQuestionnaire: !!(q && q.completed), aiReady: ai.hasKey() });
  } catch (e) { next(e); }
});

router.get('/generate', async (req, res, next) => {
  try {
    const { data: q } = await req.sb.from('questionnaire_responses').select('*').eq('user_id', req.user.id).maybeSingle();
    if (!q || !q.completed) return res.redirect('/questionnaire');
    res.render('generating', { title: 'Generating ideas', action: '/ideas/generate', label: 'Analyzing your profile and generating tailored business ideas…' });
  } catch (e) { next(e); }
});

router.post('/generate', async (req, res, next) => {
  try {
    const { data: q } = await req.sb.from('questionnaire_responses').select('*').eq('user_id', req.user.id).maybeSingle();
    if (!q || !q.completed) return res.json({ redirect: '/questionnaire' });
    const plan = planOf(req.profile);
    if (plan === 'free' && (req.profile.generations_used || 0) >= 1) {
      return res.json({ error: 'The free plan includes 1 AI idea generation. Upgrade for unlimited generations, AI roadmaps and more.', redirect: '/pricing?upgrade=1' });
    }
    

    const ideas = await ai.generateIdeas(req.accessToken, q);
    const { count } = await req.sb.from('generated_ideas').select('id', { count: 'exact', head: true }).eq('user_id', req.user.id);
    const rows = ideas.slice(0, 6).map((i, idx) => ({
      user_id: req.user.id, questionnaire_id: q.id,
      name: String(i.name || 'Untitled idea'), tagline: i.tagline || '', category: i.category || '',
      profile_summary: i.profile_summary || '', why_you: i.why_you || '',
      market_analysis: i.market_analysis || '', competitor_landscape: i.competitor_landscape || '',
      success_likelihood: Math.min(100, parseInt(i.success_likelihood, 10) || 50),
      demand_score: Math.min(10, parseInt(i.demand_score, 10) || 5),
      passion_score: Math.min(10, parseInt(i.passion_score, 10) || 5),
      time_to_revenue: i.time_to_revenue || '', startup_cost_lean: i.startup_cost_lean || '',
      startup_cost_standard: i.startup_cost_standard || '', startup_cost_full: i.startup_cost_full || '',
      legal_nuances: i.legal_nuances || '', first_steps: i.first_steps || '',
      status: 'active', position: (count || 0) + idx
    }));
    const { error } = await req.sb.from('generated_ideas').insert(rows);
    if (error) throw error;
    await awardXP(req.sb, req.user.id, req.profile, 25, 'Generated business ideas', 'generated_ideas', null);
    await req.sb.from('profiles').update({ generations_used: (req.profile.generations_used || 0) + 1 }).eq('id', req.user.id);
    // Auto-disperse the top idea's first steps into the task board with staggered deadlines (paid feature)
    try {
      const top = rows[0];
      if (plan === 'paid' && top && top.first_steps) {
        const { data: list } = await req.sb.from('task_lists').insert({ user_id: req.user.id, name: ('Idea: ' + top.name).slice(0, 60), color: '#10b981' }).select().maybeSingle();
        const steps = String(top.first_steps).split(/\n+/).map(t => t.replace(/^\s*\d+[).:-]?\s*/, '').trim()).filter(t => t.length > 3).slice(0, 7);
        const taskRows = steps.map((title, i) => ({
          user_id: req.user.id, list_id: list ? list.id : null, title: title.slice(0, 200),
          description: 'First step for "' + top.name + '" — generated by NoBossly AI.',
          priority: i === 0 ? 'high' : 'medium', status: 'todo', position: i, labels: ['idea'],
          due_date: new Date(Date.now() + (i + 1) * 3 * 86400000).toISOString().slice(0, 10)
        }));
        if (taskRows.length) await req.sb.from('tasks').insert(taskRows);
        await req.sb.rpc('push_notification', { target_user: req.user.id, ntype: 'tasks', nmessage: 'Your idea "' + top.name + '" was broken into ' + taskRows.length + ' tasks with deadlines — check your Tasks board.', nentity_type: null, nentity_id: null }).then(() => {}, () => {});
      }
    } catch (e2) { console.error('task dispersal', e2.message); }
    res.json({ redirect: '/ideas' });
  } catch (e) {
    console.error('idea generation', e);
    res.json({ error: 'Idea generation failed: ' + e.message });
  }
});

router.get('/:id', async (req, res, next) => {
  try {
    const { data: idea } = await req.sb.from('generated_ideas').select('*').eq('id', req.params.id).eq('user_id', req.user.id).maybeSingle();
    if (!idea) return res.redirect('/ideas');
    const { data: bp } = await req.sb.from('blueprints').select('id').eq('idea_id', idea.id).eq('user_id', req.user.id).maybeSingle();
    res.render('idea_detail', { title: idea.name, idea, blueprintId: bp ? bp.id : null });
  } catch (e) { next(e); }
});

router.post('/:id/favorite', async (req, res) => {
  const { data: idea } = await req.sb.from('generated_ideas').select('is_favorited').eq('id', req.params.id).eq('user_id', req.user.id).maybeSingle();
  if (idea) await req.sb.from('generated_ideas').update({ is_favorited: !idea.is_favorited }).eq('id', req.params.id);
  res.redirect('back' in req.headers ? req.headers.referer || '/ideas' : '/ideas');
});

module.exports = router;
